import React from "react";
import { Toaster } from "react-hot-toast";

import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

import { Footer, Navbar } from "@/components";
import {StateContext} from "@/contexte/StateContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Phone Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StateContext>

        <div className="layout">
          <Head>
            <title>Jhonny's Store</title>
          </Head>
          <Toaster/>
          <header>
            <Navbar />
          </header>
          <main className="main-container">{children}</main>
          <footer>
            <Footer />
          </footer>
        </div>
        </StateContext>
      </body>
    </html>
  );
}
